/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include <iostream>

using namespace std;

bool isEven(int number)
{
  return number % 2 == 0;
}

int main()
{
  int limit = 4000000;
  int sum = 0;

  int previousTerm = 1;
  int currentTerm = 2;
  int intermediateTerm;
  while (currentTerm < limit)
  {
    if (isEven(currentTerm))
    {
      sum += currentTerm;
    }
    intermediateTerm = currentTerm;
    currentTerm += previousTerm;
    previousTerm = intermediateTerm;
  }
  cout << "Result: " << sum << endl;
}
